---
title: "Events"
---

## Upcoming events

Venue: Campus North. Meetings start 6:00pm and finish around 7:30pm

Date        | Speakers | Topics          | Venue | Sign-up
----------- | -------- | --------------- |-------|--------
12-Jun-17   | [Roman Popat](https://twitter.com/rmnppt) | Automated detection of potholes using R ([abstract](abstracts.html))| Campus North | [attending.io](https://attending.io/events/r-north-june-12-2017)
26-Jun-17   | [Steph Locke](https://twitter.com/SteffLocke) | [Introduction to R](https://negroupsintrotor.eventbrite.com/?aff=rne) (9am to 5:30pm) |Room 3.19, [Herschel building](https://t.co/ijyHaakhK9). | [eventbrite](https://negroupsintrotor.eventbrite.com/?aff=rne)
26-Jun-17   | [Steph Locke](https://twitter.com/SteffLocke) | Data + Docker = Discombobulating? ([abstract](abstracts.html))| Room 3.19, [Herschel building](https://t.co/ijyHaakhK9). | [attending.io](https://attending.io/events/r-north-june-26-2017)
14-Aug-17   | TBC      | | |
09-Oct-17   | [Robin Lovelace](https://www.its.leeds.ac.uk/people/r.lovelace) | Spatial data and R | Campus North  |
11-Dec-17   | TBC      |  | |

## Past events

Date        | Speakers | Topics          | Venue
----------- | -------- | --------------- | -----
10-Apr-17   | [Matt Bashton](https://twitter.com/MattBashton)      | Shiny based brain tumour classifier
   ~          | Gholamreza Rafiee                                    | Practical subgrouping
12-Dec-16 | [Tim Brock](https://twitter.com/TimBrock_DtD) & [Rosie Hamilton](https://twitter.com/Rosicadia) | Assignments, Twitter mining and sentiment analysis |Campus North
10-Oct-16   | [Siddhant Baviskar](https://twitter.com/siddhantfri3nds)| 1 year Birthday party | Campus North
12-Sep-16   | [Colin Gillespie](https://twitter.com/csgillespie)| Optimising R and Benchmarkme package | Campus North 
15-Aug-16   |          | Lean Coffee Discussion | Campus North
11-Jul-16   |          | Lean Coffee Discussion | Campus North
09-May-16   |[Tim Brock](https://twitter.com/TimBrock_DtD)| Introduction to Grid Graphics | Campus North
11-Apr-16   |          | The apply family of functions | Campus North
14-Mar-16   |          | Mapping | Campus North
08-Feb-16   | Behrooz Mirmolavi | Mapping, rgdal and leaflet packages | Campus North
11-Jan-16   | [Dennis Prangle](https://twitter.com/dennisprangle)  | Jupyter and lightning talks | Campus North
14-Dec-15   |                 |                             | Campus North
09-Nov-15   |                 | First meet up               | Campus North
